# Generated by Django 4.1.3 on 2022-12-01 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_api', '0003_delete_account_user_agency_user_balance_user_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='user',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='number',
        ),
    ]
