# Generated by Django 4.1.3 on 2022-12-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_api', '0004_remove_user_agency_remove_user_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wage',
        ),
        migrations.AddField(
            model_name='user',
            name='agency',
            field=models.CharField(default='2582-0', max_length=6, null=True),
        ),
    ]
