# Generated by Django 4.1.3 on 2022-12-01 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_api', '0005_remove_user_wage_user_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wage',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
    ]
