# Generated by Django 4.1.3 on 2022-12-01 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_api', '0007_alter_user_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='agency',
            field=models.CharField(default='2582-0', editable=False, max_length=6),
        ),
    ]
